name: ZAP Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker-compose up -d --build

    - name: Wait for ZAP to be ready
      run: |
        echo "Waiting for ZAP to initialize..."
        sleep 30

    - name: Run ZAP scan
      run: |
        chmod +x ./scan.sh
        ./scan.sh

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap-report.html
